# Debugging of Kfact_calculator.py

## Library Import

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
#!pip install pylatex

In [2]:
# Symbolic computation
import sympy as sp

# import complex unit as: I
from sympy import I

# pritty printing sympy objects
from IPython.display import display, Latex, Math

# numerical work:
import numpy as np

# simplified looping
import itertools as it

In [3]:
import sys

sys.path.insert(1, '../')

from cgh4_calculator import cg_calc
from cgh4_calculator import print_CGmat

# Fixing big number problem

In [4]:
chosen_irreps = [(4,1),(4,1),(4,1),(4,1)]

cg = cg_calc(*chosen_irreps,verbose=True, cgdatabase="../cg_database")

#we look at the raw and non raw cg dict
cg_dict = cg.cg_dict
cg_raw = cg.raw_cg


Loading matrix representations for all the elements of H(4) ...



100%|██████████| 20/20 [00:00<00:00, 122.71it/s]



Loading the cg coefficients for the given tensor product from the database ...



100%|██████████| 59/59 [00:08<00:00,  6.72it/s]


In [14]:
#np.shape(cg_dict[7][1])

value = cg_dict[7]

np.shape(value)

#for i,imul in enumerate(value):
 #   np.shape(imul)

block = value[1]
np.shape(block)

op = block[:,2]
op

#[1][:,2]

(3, 256, 3)

(256, 3)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1.00000000000000, 0, 0, -1.00000000000000, 0, 0, 0,
       0, 0, 0, 0, 0, -2.70215977642230e+16, 0, 0, 0, 0, 0,
       2.70215977642230e+16, 0, 0, 0, 0, 0, 0, 0, 0,
       -2.70215977642230e+16, 0, 0, 2.70215977642230e+16, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.00000000000000, 0, 0,
       -1.00000000000000, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2.70215977642230e+16, 0, 0, 0, 0, 0, 0, 0, 0,
       -2.70215977642230e+16, 0, 0, 0, 0, 0, 2.70215977642230e+16, 0, 0,
       0, 0, 0, -2.70215977642230e+16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, -2.70215977642230e+16, 0, 0, 0, 0, 0, 2.70215977642230e+16,
       0, 0, 0, 0, 0, 2.70215977642230e+16, 0, 0, 0, 0, 0, 0, 0, 0,
       -2.70215977642230e+16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 5.40431955284459e+16, 0, 0, -5.40431955284459e+16,
       0, 0, 0, 0, 0, 0,

In [31]:
#function used to round the raw CG matrix obtained from the calculator #TO DO: include this function at the end of the cg_calculator class
def new_round_CG(cgmat: np.ndarray, digits:int=2) -> np.ndarray:
    """
    Function rounding the matrices of Clebsch-Gordan coefficients coming out of the cg calculator
    
    Input:
        - cgmat: the raw cg matrix coming out of the cg calculator
        
    Output:
        - rounded cgmat: the cg matrix with rounded numbers
    """

    #ok = np.asarray(cgmat)
    #print(np.shape(ok))
    #return np.round(np.asarray(cgmat).astype(np.float64),digits)

    #first thing first we convert the sympy symbols to floats
    new_cgmat = np.asarray(cgmat).astype(np.float64)

    #then we normalize the entries to the columns to the highest number
    for j in range(np.shape(new_cgmat)[1]):
    
        #index = (new_cgmat[:,j]!=0).argmax(axis=0)
        index = np.abs(new_cgmat[:,j]).argmax(axis=0)
        norm = new_cgmat[index,j]
    
        new_cgmat[:,j] /= norm

    #then we put to 0 the coefficient smaller than a fixed treshold
    treshold = 10**(-10)
    new_cgmat[np.abs(new_cgmat)<treshold] = 0.0    

    #then we return the rounded matrix
    return np.round(new_cgmat,digits)

In [30]:
numblock = np.asarray(block).astype(np.float64)

#numblock[:,2]

index = (numblock[:,2]!=0).argmax(axis=0)

index

(numblock[:,2]!=0)

#for n in numblock[:,2]:
#    n
#    n>0

#numblock[index,2]

np.int64(27)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False,

In [32]:
new_block = new_round_CG(block)

np.shape(new_block)

newop = new_block[:,2]

newop

(256, 3)

array([ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0. ,  0. ,  0. ,  0. ,
        0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,
        0. ,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,  0. ,
        0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0. ,  0. ,  0. ,  0. , -0.5,
        0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. ,  0. ,  0. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0.5,  0. ,
        0. ,  0. ,  0. ,  0. ,  0.5,  0. ,  0. ,  0

## Smaller test

In [9]:
chosen_irreps = [(4,1),(4,1)]

cg = cg_calc(*chosen_irreps,verbose=True, cgdatabase="../cg_database")

#we look at the raw and non raw cg dict
cg_dict = cg.cg_dict
cg_raw = cg.raw_cg


Loading matrix representations for all the elements of H(4) ...


Loading the cg coefficients for the given tensor product from the database ...



In [10]:
cg_dict.keys()
cg_raw.keys()

dict_keys([0, 6, 14, 16])

dict_keys([(0, 0), (16, 0), (6, 0), (14, 0)])

In [21]:
sp.Matrix(cg_dict[0][0])

sp.Matrix(cg_raw[(0,0)])

Matrix([
[1.0],
[  0],
[  0],
[  0],
[  0],
[1.0],
[  0],
[  0],
[  0],
[  0],
[1.0],
[  0],
[  0],
[  0],
[  0],
[1.0]])

Matrix([
[96.0*A[0, 0] + 96.0*A[5, 0] + 96.0*A[10, 0] + 96.0*A[15, 0]],
[                                                          0],
[                                                          0],
[                                                          0],
[                                                          0],
[96.0*A[0, 0] + 96.0*A[5, 0] + 96.0*A[10, 0] + 96.0*A[15, 0]],
[                                                          0],
[                                                          0],
[                                                          0],
[                                                          0],
[96.0*A[0, 0] + 96.0*A[5, 0] + 96.0*A[10, 0] + 96.0*A[15, 0]],
[                                                          0],
[                                                          0],
[                                                          0],
[                                                          0],
[96.0*A[0, 0] + 96.0*A[5, 0] + 96.0*A[10, 0] +

In [22]:
sp.Matrix(cg_dict[6][0])

sp.Matrix(cg_raw[(6,0)])

Matrix([
[              1.0,                  1.0,                   1.0],
[                0,                    0,                     0],
[                0,                    0,                     0],
[                0,                    0,                     0],
[                0,                    0,                     0],
[0.999999999999997,                  1.0,                  -1.0],
[                0,                    0,                     0],
[                0,                    0,                     0],
[                0,                    0,                     0],
[                0,                    0,                     0],
[0.999999999999997,    -2.00000000000001, -6.75385673313636e-16],
[                0,                    0,                     0],
[                0,                    0,                     0],
[                0,                    0,                     0],
[                0,                    0,                     0],
[

Matrix([
[           10.6666666666667*A[0, 1] + 15.084944665313*A[0, 2] + 26.1278905896872*A[0, 3] + 10.6666666666667*A[5, 1] + 15.084944665313*A[5, 2] - 26.1278905896872*A[5, 3] + 10.6666666666667*A[10, 1] - 30.1698893306261*A[10, 2] - 32.0*A[15, 1],      15.084944665313*A[0, 1] + 21.3333333333334*A[0, 2] + 36.950417228136*A[0, 3] + 15.084944665313*A[5, 1] + 21.3333333333333*A[5, 2] - 36.950417228136*A[5, 3] + 15.084944665313*A[10, 1] - 42.6666666666667*A[10, 2] - 45.2548339959391*A[15, 1],   26.1278905896872*A[0, 1] + 36.950417228136*A[0, 2] + 64.0*A[0, 3] + 26.1278905896872*A[5, 1] + 36.950417228136*A[5, 2] - 64.0*A[5, 3] + 26.1278905896872*A[10, 1] - 73.900834456272*A[10, 2] - 78.3836717690616*A[15, 1]],
[                                                                                                                                                                                                                                               0,                                        

In [23]:
chosen_irreps = [(4,1),(4,1), (4,1)]

cg = cg_calc(*chosen_irreps,verbose=True, cgdatabase="../cg_database")

#we look at the raw and non raw cg dict
cg_dict = cg.cg_dict
cg_raw = cg.raw_cg


Loading matrix representations for all the elements of H(4) ...


Loading the cg coefficients for the given tensor product from the database ...



In [24]:
cg_dict.keys()
cg_raw.keys()

dict_keys([10, 11, 13, 18, 19])

dict_keys([(10, 2), (18, 1), (18, 2), (10, 3), (19, 0), (10, 0), (18, 0), (10, 1), (11, 0), (19, 1), (13, 0)])

In [25]:
sp.Matrix(cg_dict[10][0])

sp.Matrix(cg_raw[(10,0)])

Matrix([
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0, 1.0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0, 1.0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0, 1.0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[1.0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0, 1.0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0, 1.0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[1.0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0, 1.0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[  0,   0,   0,   0],
[

Matrix([
[                                                                                                                                96.0*A[0, 0] + 96.0*A[21, 1] + 96.0*A[42, 2] + 96.0*A[63, 3],                                                                                                                                                                                            0,                                                                                                                                                                                            0,                                                                                                                                                                                            0],
[                                                                                                                                                                                           0,   32.0*A[1, 1] + 32.0*A[2, 2] + 32.0*A

## Reproducing issue from class file

In [5]:
chosen_irreps = [(4,1),(4,1),(4,1),(4,1)]

cg = cg_calc(*chosen_irreps,verbose=True, force_computation=True)

#we compute the cg coefficient using the ad hoc class and we store them in a tmp dictionary
cg_dict_tmp = cg.cg_dict


mul = cg.get_multiplicities()
mul


#sp.Matrix(cg_dict_tmp[0][0])

np.shape(cg_dict_tmp[17][0])
sp.Matrix(cg_dict_tmp[17][0])


Loading matrix representations for all the elements of H(4) ...


Computing the cg coefficients for the given tensor product ...


Looping over group elements...



  2%|▏         | 6/384 [35:49<37:36:37, 358.19s/it]


KeyboardInterrupt: 

In [10]:
rawcg = cg.raw_cg
rawcg
#rawcg[(18,0)]

AttributeError: 'cg_calc' object has no attribute 'raw_cg'