In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Library Imports

In [2]:
# Symbolic computation
import sympy as sp

# import complex unit as: I
from sympy import I

# pritty printing sympy objects
from IPython.display import display, Latex, Math

# numerical work:
import numpy as np

# simplified looping
import itertools as it

In [22]:
import sys

sys.path.insert(1, '../')

from cgh4_calculator import cg_calc
from cgh4_calculator import print_CGmat

# From available notebooks

In [4]:
#we instantiate the gamma matrices
gamma1 = sp.Matrix([
            [0,0,0,I],
            [0,0,I,0],
            [0,-I,0,0],
            [-I,0,0,0]
])
gamma2 = sp.Matrix([
            [0,0,0,-1],
            [0,0,1,0],
            [0,1,0,0],
            [-1,0,0,0]
])
gamma3 = sp.Matrix([
            [0,0,I,0],
            [0,0,0,-I],
            [-I,0,0,0],
            [0,I,0,0]
])
gamma4 = sp.Matrix([
            [0,0,1,0],
            [0,0,0,1],
            [1,0,0,0],
            [0,1,0,0]
])

#and the symbolic counterpart
gamma1_s = sp.Symbol("gamma_1")
gamma2_s = sp.Symbol("gamma_2")
gamma3_s = sp.Symbol("gamma_3")
gamma4_s = sp.Symbol("gamma_4")





#we can now instantiate the gamma_mu vector
gamma_mu = [gamma1,gamma2,gamma3,gamma4]#,gamma_5]
gamma_mu_s = [gamma1_s,gamma2_s,gamma3_s,gamma4_s]#,sym_gamma_5]

sp.Matrix(gamma_mu_s)

Matrix([
[gamma_1],
[gamma_2],
[gamma_3],
[gamma_4]])

In [5]:
#same thing for gamma5 and for the identity
# gamma_5
gamma5 = sp.Matrix([
            [1,0,0,0],
            [0,1,0,0],
            [0,0,-1,0],
            [0,0,0,-1]
])
gamma5_s = sp.Symbol("gamma_5")
gamma5_s

# also the 4D identity matrix can come in handy:
Id_4 = sp.Matrix(
        [
            [1,0,0,0],
            [0,1,0,0],
            [0,0,1,0],
            [0,0,0,1]
        ]
)

gamma_5

In [6]:
#we compute the polarization matrix
Gamma_pol = 0.5*(Id_4 + gamma4) @ (Id_4 - I * gamma1 @ gamma2)
sp.Matrix(Gamma_pol)

Gamma_pol_s = sp.Symbol("Gamma_pol")
Gamma_pol_s

Matrix([
[0,   0, 0,   0],
[0, 1.0, 0, 1.0],
[0,   0, 0,   0],
[0, 1.0, 0, 1.0]])

Gamma_pol

In [7]:
#showcase of latex skills
#display(Math(r'\{} ='.format(Gamma_pol_s) ) )
#sp.Matrix(Gamma_pol)

In [8]:
Gamma_pol * gamma4

Matrix([
[0,   0, 0,   0],
[0, 1.0, 0, 1.0],
[0,   0, 0,   0],
[0, 1.0, 0, 1.0]])

In [9]:
mN = sp.Symbol("m_N")
E = sp.Symbol("E(p)")
cO = sp.Symbol("c_O")
p = [
    sp.Symbol("p_1"),
    sp.Symbol("p_2"),
    sp.Symbol("p_3"),
    I*E # = sp.Symbol("p_4")
]

sp.Matrix(p)

Matrix([
[   p_1],
[   p_2],
[   p_3],
[I*E(p)]])

In [10]:
#we compute pslash
pslash = np.einsum('ijk,i->jk',gamma_mu,p)
sp.Matrix(pslash)

pslash_s = sp.Symbol("\cancel{p}")
pslash_s

Matrix([
[             0,              0, I*E(p) + I*p_3,    I*p_1 - p_2],
[             0,              0,    I*p_1 + p_2, I*E(p) - I*p_3],
[I*E(p) - I*p_3,   -I*p_1 + p_2,              0,              0],
[  -I*p_1 - p_2, I*E(p) + I*p_3,              0,              0]])

\cancel{p}

In [11]:
#showcase of latex skills
#display(Math(r'{} ='.format(pslash_s) ) )
#sp.Matrix(pslash)

In [12]:
sp.Matrix( -I*pslash  + mN*Id_4)

Matrix([
[                m_N,                   0, -I*(I*E(p) + I*p_3),    -I*(I*p_1 - p_2)],
[                  0,                 m_N,    -I*(I*p_1 + p_2), -I*(I*E(p) - I*p_3)],
[-I*(I*E(p) - I*p_3),   -I*(-I*p_1 + p_2),                 m_N,                   0],
[  -I*(-I*p_1 - p_2), -I*(I*E(p) + I*p_3),                   0,                 m_N]])

In [13]:
num_s = (Gamma_pol_s * (- I * pslash_s + mN)  ).simplify(rational=True)
num_s 

num = (Gamma_pol * (- complex(0,1) * pslash + mN*Id_4)  )#.simplify(rational=True)
num

Gamma_pol*(-I*\cancel{p} + m_N)

Matrix([
[                    0,                                0,                    0,                                0],
[-1.0*I*(-I*p_1 - p_2), 1.0*m_N - 1.0*I*(I*E(p) + I*p_3), -1.0*I*(I*p_1 + p_2), 1.0*m_N - 1.0*I*(I*E(p) - I*p_3)],
[                    0,                                0,                    0,                                0],
[-1.0*I*(-I*p_1 - p_2), 1.0*m_N - 1.0*I*(I*E(p) + I*p_3), -1.0*I*(I*p_1 + p_2), 1.0*m_N - 1.0*I*(I*E(p) - I*p_3)]])

In [14]:
Tr_num = sp.trace(num).simplify(rational=True)
Tr_num

2*E(p) + 2*m_N

# New: general denominator computation

## first attempts

In [15]:
operator_s = sp.Symbol('O')

#den_s = (Gamma_pol_s @ (- I @ pslash_s + mN) @ operator_s @ (- I @ pslash_s + mN)  )#.simplify(rational=True)
#den_s

In [16]:
#compute cg coefficients for the vector case
cgV = cg_calc((4,1),(4,1))


Loading matrix representations for all the elements of H(4) ...


Loading the cg coefficients for the given tensor product from the database ...



In [17]:
cgV.cg_dict.keys()
cgV.get_multiplicities()

dict_keys([0, 6, 14, 16])

[1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0]

In [35]:
cg11 = np.squeeze( cgV.cg_dict[0][0] )
cg11

array([1.00000000000000, 0, 0, 0, 0, 1.00000000000000, 0, 0, 0, 0,
       1.00000000000000, 0, 0, 0, 0, 1.00000000000000], dtype=object)

In [38]:
np.shape(cg11)
np.shape(gamma_mu)
np.shape(p)

(16,)

(4, 4, 4)

(4,)

In [49]:
'1' *3

'111'

In [87]:
[str( int(np.base_repr(i,4))  ) for i in range(4**n)]

['0',
 '1',
 '2',
 '3',
 '10',
 '11',
 '12',
 '13',
 '20',
 '21',
 '22',
 '23',
 '30',
 '31',
 '32',
 '33']

In [103]:
n = 2
#for i in range(4**n):
 #   str( int(np.base_repr(i,4)) +  int('1' * n) )

mapping =np.asarray( [ tuple(j) for j in [str( int(np.base_repr(i,4)) +  int('1' * n) ) for i in range(4**n)] ] , dtype=int) -1
#mapping =np.asarray( [ tuple(j) for j in [str( int(np.base_repr(i,4))  ) for i in range(4**n)] ], dtype=int)
mapping

array([[0, 0],
       [0, 1],
       [0, 2],
       [0, 3],
       [1, 0],
       [1, 1],
       [1, 2],
       [1, 3],
       [2, 0],
       [2, 1],
       [2, 2],
       [2, 3],
       [3, 0],
       [3, 1],
       [3, 2],
       [3, 3]])

In [89]:
mapping[3] -1

array([0, 3])

In [104]:
cg_mat[*mapping[0]]

np.float64(0.0)

In [108]:
for i in range(4**n):
    #mapping[i]
    #cg11[i]
    cg_mat[*mapping[i]] = cg11[i]

In [107]:
cg_mat

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
(4,) * 2

(4, 4)

In [61]:
n=2
cg_mat = np.zeros(shape=(4,)*n)
cg_mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [109]:
#let's try the contraction
op = np.einsum('ij,ikl,j -> kl',cg_mat,gamma_mu,p)

sp.Matrix( op )


Matrix([
[                     0,                      0, 1.0*I*E(p) + 1.0*I*p_3,    1.0*I*p_1 - 1.0*p_2],
[                     0,                      0,    1.0*I*p_1 + 1.0*p_2, 1.0*I*E(p) - 1.0*I*p_3],
[1.0*I*E(p) - 1.0*I*p_3,   -1.0*I*p_1 + 1.0*p_2,                      0,                      0],
[  -1.0*I*p_1 - 1.0*p_2, 1.0*I*E(p) + 1.0*I*p_3,                      0,                      0]])

In [110]:
den = Gamma_pol @ (- complex(0,1) * pslash + mN*Id_4) @ op @ (- complex(0,1) * pslash + mN*Id_4)

trden = sp.trace(den).simplify(rational=True)

trden

(Tr_num/trden).simplify(rational=True)

2*I*(E(p)**3 + 2*E(p)**2*m_N + E(p)*m_N**2 - E(p)*p_1**2 - E(p)*p_2**2 - E(p)*p_3**2 - 2*m_N*p_1**2 - 2*m_N*p_2**2 - 2*m_N*p_3**2)

I*(E(p) + m_N)/(-E(p)**3 - 2*E(p)**2*m_N - E(p)*m_N**2 + E(p)*p_1**2 + E(p)*p_2**2 + E(p)*p_3**2 + 2*m_N*p_1**2 + 2*m_N*p_2**2 + 2*m_N*p_3**2)

## computation

In [111]:
cgV = cg_calc((4,1),(4,1))


Loading matrix representations for all the elements of H(4) ...


Loading the cg coefficients for the given tensor product from the database ...



In [127]:
#cg11 = np.squeeze( cgV.cg_dict[0][0] )
cg11 = cgV.cg_dict[0][0][:,0]
cg31_1 = cgV.cg_dict[6][0][:,0]

In [125]:
cg31_1[0

(16,)

In [129]:
n=2

mapping =np.asarray( [ tuple(j) for j in [str( int(np.base_repr(i,4)) +  int('1' * n) ) for i in range(4**n)] ] , dtype=int) -1

cg_mat = np.zeros(shape=(4,)*n)

for i in range(4**n):
    cg_mat[*mapping[i]] = cg31_1[i] #cg11[i]

In [130]:
op = np.einsum('ij,ikl,j -> kl',cg_mat,gamma_mu,p)

In [131]:
den = Gamma_pol @ (- complex(0,1) * pslash + mN*Id_4) @ op @ (- complex(0,1) * pslash + mN*Id_4)

trden = sp.trace(den).simplify(rational=True)

(Tr_num/trden).simplify(rational=True)

I*(E(p) + m_N)/(3*E(p)**3 + 6*E(p)**2*m_N + 3*E(p)*m_N**2 + 5*E(p)*p_1**2 + 5*E(p)*p_2**2 + 5*E(p)*p_3**2 + 2*m_N*p_1**2 + 2*m_N*p_2**2 + 2*m_N*p_3**2)